[package]
name = "openlight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
norm = { version = "0.1.1", features = ["fzf-v2"] }
walkdir = "2.5.0"
xdgkit = "3.2.5"
